# Generated by Django 4.2.6 on 2023-10-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='528bb3d5-e81a-4acf-9098-3117d4ce5701', on_delete=django.db.models.deletion.CASCADE, to='core.usertype'),
            preserve_default=False,
        ),
    ]
