# Generated by Django 4.2.6 on 2023-10-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
