# Generated by Django 4.2.6 on 2023-10-24 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.TextField(max_length=1000)),
                ('available_amount', models.IntegerField()),
                ('price', models.FloatField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.size')),
            ],
        ),
    ]
