# Generated by Django 4.2.6 on 2023-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='type',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
