# Generated by Django 4.2.6 on 2023-10-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_size_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
