# Generated by Django 4.2.6 on 2023-10-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_size_created_at_size_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
