# Generated by Django 4.2.6 on 2023-10-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rename_item_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available_amount',
            new_name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='bardcode',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
