# Generated by Django 4.2.6 on 2023-10-24 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0013_sbanner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sBanner',
            new_name='Banner',
        ),
    ]
