# Generated by Django 4.2.6 on 2023-10-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_rename_sbanner_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='to_product',
            field=models.ForeignKey(default='5abca141-6291-4470-a877-3f23704c2441', on_delete=django.db.models.deletion.CASCADE, to='items.product'),
            preserve_default=False,
        ),
    ]
